# Generated by Django 5.2.17 on 2026-08-17 14:30

import apps.muestras.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(blank=True, max_length=200, verbose_name='nombre de comercio')),
                ('giro', models.CharField(blank=True, choices=[('CHOCOLATE_ARTESANAL', 'Chocolate artesanal'), ('CACAO_Y_DERIVADOS', 'Cacao y derivados'), ('REPOSTERIA', 'Repostería'), ('BEBIDAS_TRADICIONALES', 'Bebidas tradicionales'), ('GASTRONOMIA_TABASQUENA', 'Gastronomía tabasqueña'), ('ARTESANIAS', 'Artesanías'), ('TURISMO_EXPERIENCIAS', 'Turismo y experiencias'), ('MODA_Y_DISENO', 'Moda y diseño'), ('TECNOLOGIA_LOCAL', 'Tecnología local'), ('SERVICIOS_EMPRESARIALES', 'Servicios empresariales')], max_length=64, verbose_name='giro')),
                ('programa_especial', models.CharField(blank=True, choices=[('ORIGEN_TABASCO', 'Origen Tabasco'), ('TANDAS_MUJER', 'Tandas para la Mujer'), ('CODIGO_BARRAS', 'Código de Barras')], max_length=64, verbose_name='programa especial')),
                ('logo', models.FileField(blank=True, null=True, upload_to=apps.muestras.models._ruta_logo, verbose_name='logo del comercio')),
                ('paso_actual', models.PositiveSmallIntegerField(default=1, verbose_name='paso actual')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_muestra', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'solicitud de muestra',
                'verbose_name_plural': 'solicitudes de muestra',
            },
        ),
        migrations.CreateModel(
            name='ImagenComercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.muestras.models._ruta_imagen, verbose_name='imagen')),
                ('nombre_original', models.CharField(blank=True, max_length=255, verbose_name='nombre original')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='muestras.solicitudmuestra', verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'imagen del comercio',
                'verbose_name_plural': 'imágenes del comercio',
                'ordering': ['fecha_carga'],
            },
        ),
    ]
