# Generated by Django 5.2.17 on 2026-09-15 18:49

import apps.muestras.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0008_solicitud_validacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamientoAdicionalSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=150, verbose_name='nombre de equipo')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('modelo', models.CharField(blank=True, max_length=150, verbose_name='modelo')),
                ('foto', models.FileField(blank=True, upload_to=apps.muestras.models._ruta_foto_equipamiento, verbose_name='foto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_equipamiento_adicional', to='muestras.solicitudmuestra')),
            ],
            options={
                'verbose_name': 'equipamiento adicional',
                'verbose_name_plural': 'equipamientos adicionales',
            },
        ),
    ]
