# Generated by Django 5.2.17 on 2026-08-17 08:56

import apps.expediente.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=64, unique=True, verbose_name='clave')),
                ('etiqueta', models.CharField(max_length=150, verbose_name='etiqueta')),
                ('tipo_dato', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('FECHA', 'Fecha'), ('BOOLEANO', 'Sí/No')], default='TEXTO', max_length=16, verbose_name='tipo de dato')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='obligatorio')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('tipos_persona', models.JSONField(blank=True, default=list, verbose_name='tipos de persona')),
            ],
            options={
                'verbose_name': 'campo adicional',
                'verbose_name_plural': 'campos adicionales',
                'ordering': ['orden', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=64, unique=True, verbose_name='clave')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('dias_vigencia', models.PositiveIntegerField(blank=True, help_text='Si hay emisión y no hay vencimiento, se calcula con este valor.', null=True, verbose_name='días de vigencia')),
                ('tipos_persona', models.JSONField(blank=True, default=list, verbose_name='tipos de persona')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(blank=True, choices=[('PERSONA_FISICA', 'Persona física'), ('PERSONA_MORAL', 'Persona moral'), ('CIUDADANO', 'Ciudadano')], max_length=32, verbose_name='tipo de persona')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expediente', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'expediente',
                'verbose_name_plural': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, help_text='Nombre(s) o razón social según el tipo de persona.', max_length=150, verbose_name='nombres / razón social')),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, verbose_name='apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='apellido materno')),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto')),
                ('domicilio', models.CharField(blank=True, max_length=255, verbose_name='domicilio')),
                ('representante_legal', models.CharField(blank=True, help_text='Obligatorio para persona moral.', max_length=200, verbose_name='representante legal')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_generales', to='expediente.expediente', verbose_name='expediente')),
            ],
            options={
                'verbose_name': 'datos generales',
                'verbose_name_plural': 'datos generales',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expediente.expediente', verbose_name='expediente')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='expediente.tipodocumento', verbose_name='tipo de documento')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=apps.expediente.models.private_document_storage, upload_to=apps.expediente.models._ruta_version_documento, verbose_name='archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='nombre original')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('hash_sha256', models.CharField(blank=True, max_length=64, verbose_name='hash SHA-256')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='expediente.documento', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'versión de documento',
                'verbose_name_plural': 'versiones de documento',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='version_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expediente.versiondocumento', verbose_name='versión actual'),
        ),
        migrations.CreateModel(
            name='ValorCampoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.JSONField(blank=True, null=True, verbose_name='valor')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='expediente.campoadicional', verbose_name='campo')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_adicionales', to='expediente.expediente', verbose_name='expediente')),
            ],
            options={
                'verbose_name': 'valor de campo adicional',
                'verbose_name_plural': 'valores de campos adicionales',
                'constraints': [models.UniqueConstraint(fields=('expediente', 'campo'), name='uniq_valor_campo_por_expediente')],
            },
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('expediente', 'tipo_documento'), name='uniq_documento_tipo_por_expediente'),
        ),
    ]
