# Generated by Django 5.2.17 on 2026-09-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0007_mobiliario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, verbose_name='representante legal'),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='número de celular'),
        ),
    ]
