# Generated by Django 5.2.17 on 2026-09-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='boletab_evento_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='evento de Boletab'),
        ),
        migrations.AddField(
            model_name='evento',
            name='boletab_evento_nombre',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
