# Generated by Django 5.2.17 on 2026-09-09 22:50

from django.db import migrations, models


def preserve_boletab_relationships(apps, schema_editor):
    Evento = apps.get_model("landingpage", "Evento")
    for event in Evento.objects.exclude(boletab_evento_id=""):
        event.boletab_eventos = [
            {"id": event.boletab_evento_id, "name": event.boletab_evento_nombre}
        ]
        event.save(update_fields=["boletab_eventos"])


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_evento_boletab_evento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='boletab_eventos',
            field=models.JSONField(blank=True, default=list, verbose_name='eventos de Boletab'),
        ),
        migrations.RunPython(
            preserve_boletab_relationships,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='evento',
            name='boletab_evento_id',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='boletab_evento_nombre',
        ),
    ]
