# Generated by Django 5.2.17 on 2026-09-09 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_remove_evento_boletab_evento_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boletab_evento_id', models.CharField(max_length=100)),
                ('asiento_id', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(blank=True, max_length=250)),
                ('giros', models.JSONField(blank=True, default=list)),
                ('subgiros', models.JSONField(blank=True, default=list)),
                ('folios', models.JSONField(blank=True, default=list)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_espacios', to='landingpage.evento')),
            ],
            options={
                'verbose_name': 'regla de espacio',
                'verbose_name_plural': 'reglas de espacios',
                'constraints': [models.UniqueConstraint(fields=('evento', 'boletab_evento_id', 'asiento_id'), name='regla_unica_por_espacio_boletab')],
            },
        ),
    ]
