# Generated by Django 5.2.17 on 2026-09-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_reglaespacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglaespacio',
            name='reglas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
