# Generated by Django 5.2.17 on 2026-09-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_evento_documentos_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='equipamiento_obligatorio',
            field=models.JSONField(blank=True, default=list, verbose_name='equipamiento obligatorio'),
        ),
    ]
